// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cars.Models
{
    public partial class Car
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string Brand { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string Model { get; set; }
        public int Year { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Price { get; set; }
        public bool New { get; set; }
        public int UserId { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Cars")]
        public virtual User User { get; set; }
    }
}