// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cars.Models
{
    public partial class User
    {
        public User()
        {
            Cars = new HashSet<Car>();
        }

        [Key]
        public int UserId { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string UserName { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string PasswordHash { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string PhoneNumber { get; set; }
        [Required]
        [StringLength(250)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string LastName { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Car> Cars { get; set; }
    }
}